export default {
    eng:"الإنجليزية",
    ara:"عربي",
    nxt:"التالي",
    wel:"مرحبًا",
    signtxt:"تسجيل الدخول للاستمتاع بعملية الدفع الأسرع والأسهل",
    google:"المتابعة مع جوجل",
    facebook:"المتابعة مع فيسبوك",
    apple:"المتابعة مع آبل",
    contwithEmail:"المتابعة باستخدام البريد الإلكتروني / الجوال",
    newTogeekay:"جديد في Geekay؟",
    createAcc:"إنشاء حساب",
    byContinuing:"من خلال الاستمرار، فإنك توافق على شروط Geekay",
    TermAndCondition:"الأحكام والشروط",
    and:"و",
    PrivacyAndPolicy:"سياسة الخصوصية",
    continueAsGuest:"المتابعة كضيف",
    EmailandPhone:"البريد الإلكتروني / الجوال",
    password:"كلمة السر",
    login:"تسجيل الدخول",
    forgotPass:"نسيت كلمة السر؟",
    gautam:"جوتام",
    bedi:"بيدي",
    dob:"تاريخ الميلاد",
    gender:"الجنس",
    mobilenum:"رقم الجوال",
    email:"البريد الإلكتروني",
    conPass:"تأكيد كلمة السر",
    creatAcctxt:"إنشاء حساب",
    register:"تسجيل",
    alreadyAcc:"هل لديك حساب؟ تسجيل الدخول",
    facebk:"فيسبوك",
    ggl:"جوجل",
    iTunes:"تسجيل الدخول باستخدام iTunes",
    mxgp:"خمس ليالٍ في فيريدي الأساسية",
    firstNight:"MXGP 2020: الفيديو الرسمي للدراجات النارية",
    msi:"Five N الأساسية",
    aed:"درهم ",
    num:"159",
    aed2:"درهم 359.00",
    off:"خصم 20%",
    releasedate:"الإصدار في 12 يناير 2021",
    released:"تم الإصدار",
    viewall:"عرض الكل",
    coming:"قريبًا",
    gamingcont:"وحدات التحكم في الألعاب",
    chair:"أثاث الألعاب",
    headphone:"سماعات الألعاب",
    newRelease:"إصدار جديد",
    bestSelle:"الأكثر مبيعًا",
    newproduct:"منتجات جديدة",
    laptops:"الكمبيوترات المحمولة",
    prebuiltpc:"أجهزة الكمبيوتر المحمولة المُعدة مسبقًا",
    comingsoon:"قريبًا",
    onsale:"تخفيض!",
    pcandlaptop:"أجهزة الكمبيوتر والكمبيوتر المحمول",
    geeknation:"أمة الأذكياء",
    fname:"الاسم الأول",
    lname:"اسم العائلة",
    show:"عرض",
    hide :"إخفاء",
    signuptogetLatestUpdate:"سجل للحصول على آخر التحديثات من Geekay",
    or:"أو",
    signin:"تسجيل الدخول",
    shopbycategory:"تسوق حسب الفئة",
    chooseYourlang:"اختر لغتك",
    alertText:"الرجاء تأكيد كلمة السر",
    chooseYourlang:"Choose Your Language",
};