export default {
  headerback: require("../assets/images/geekay.png"),
  headerLogo: require("../assets/images/geekay_logo_one@3x.png"),
  headerBackIc: require("../assets/images/ic_back_main.png"),
  google: require("../assets/images/ic_google_second.png"),
  facebook: require("../assets/images/ic_facebook_second.png"),
  apple: require("../assets/images/apple.png"),
  checkBox: require("../assets/images/ic_checkbox.png"),
  cart: require("../assets/images/ic_cart.png"),
  search: require("../assets/images/ic_search.png"),
  hitman: require("../assets/images/Hitman.jpg"),
  troy: require("../assets/images/troy.jpg"),
  wanted: require("../assets/images/Wanted.jpg"),
  remote: require("../assets/images/remote2.png"),
  gogle: require("../assets/images/gogle.jpg"),
  coffee: require("../assets/images/coffee.webp"),
  back: require("../assets/images/ic_back.png"),
  forward: require("../assets/images/ic_forward@2x.png"),
  msi: require("../assets/images/msirtx.png"),
  mxgp: require("../assets/images/mxgp.jpg"),
  firstNight: require("../assets/images/firstnightatfreddy.webp"),
  chair:require("../assets/images/chair.webp"),
  headPhone:require("../assets/images/earphone.webp"),
  pcandlaptop:require("../assets/images/pcandlaptop.jpg"),
  geeknation:require("../assets/images/geeknation.png"),
  home:require("../assets/images/ic_home@2x.png"),
  category:require("../assets/images/ic_categories_inactive@2x.png"),
  giftcard:require("../assets/images/ic_gift_inactive@2x.png"),
  profile:require("../assets/images/ic_profile_inactive@2x.png"),
  social:require("../assets/images/ic_social_inactive@2x.png"),
  radiocheck:require("../assets/images/checkedRadio.png"),
  radionotcheck:require("../assets/images/notCheckedRadio.png"),
  apple2:require("../assets/images/ic_apple@2x.png")

};
