export default {
    eng:"English",
    ara:"Arabic",
    nxt:"NEXT",
    wel:"Welcome",
    signtxt:"Sign-in to enjoy easier & faster checkout",
    google:"Continue with Google",
    facebook:"Continue with Facebook",
    apple:"Continue with Apple",
    contwithEmail:"Continue with Email / Mobile",
    newTogeekay:"New to Geekay?",
    createAcc:"Create an account",
    byContinuing:" By continuing, you agree to Geekay's",
    TermAndCondition:"Terms & Conditions",
    and:"and",
    PrivacyAndPolicy:"Privacy Policy",
    continueAsGuest:"Continue as Guest",
    EmailandPhone:"Email / Mobile",
    password:"Password",
    login:"LOGIN",
    forgotPass:"Forgot Password?",
    gautam:"Gautam",
    bedi:"Bedi",
    dob:"DOB",
    gender:"Gender",
    mobilenum:"Mobile Number",
    email:"Email ID",
    conPass:"Confirm Password",
    creatAcctxt:"Create an account",
    register:"REGISTER",
    alreadyAcc:"Already have an account? Login",
    facebk:"Facebook",
    ggl:"Google",
    iTunes:"Sign in with with iTunes",
    mxgp:"Five Nights at Freddy Core collection",
    firstNight:"MXGP 2020: The Official Motorcross Video",
    msi:"Five N                     core",
    aed:"AED ",
    num:"159",
    aed2:"AED 359.00",
    off:"20%OFF",
    releasedate:"Releasing 12 jan 2021",
    released:"Released",
    viewall:"VIEW ALL",
    coming:"Coming Soon",
    gamingcont:"Gaming Controllers",
    chair:"Gaming Furniture",
    headphone:"Gaming Headsets",
    newRelease:"New Release",
    bestSelle:"Best Seller's",
    newproduct:"New Products",
    laptops:"Laptop's",
    prebuiltpc:"Pre-Built PC's",
    comingsoon:"Coming Soon",
    onsale:"On Sale!",
    pcandlaptop:"PC & Laptop's",
    geeknation:"Geek Nation",
    fname:"FirstName",
    lname:"LastName",
    show:"Show",
    hide :"Hide",
    signuptogetLatestUpdate:"Sign up to recieve latest updates from Geekay",
    or:"OR",
    signin:"Sign-In",
    shopbycategory:"Shop by category",
    chooseYourlang:"Choose your language",
    alertText:"PLEASE CONFIRM YOUR PASSWORD"
};